[project]
name = "nghiango-asteroids"
version = "1.0.1"
dependencies = [
    "pygame",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["asteroids"]

[project.scripts]
asteroids = "asteroids:main"
