[project]
name = "nghiango-static-site-generator"
version = "0.2.6"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["src"]
